name: Build Custom Alterra Bazzite Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Custom System Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: --no-sign
    steps:
      - name: Checkout Project Repository Tree
        uses: actions/checkout@v4

      - name: Force Build and Compile Core OS Image
        uses: blue-build/github-action@v1
        with:
          recipe: 'recipe.yml'
          registry_token: ${{ github.token }}
          prune: true
          # ADD THE NO-SIGN FLAG TO BYPASS THE KEY ERROR
          extra_flags: '--no-sign'
